### ISSUE TITLE
robosense timestamp

### ISSUE THREAD

**Issue by chengwei0427** [HViktorTsoi/PV-LIO#1]
Hi, @HViktorTsoi 
Thanks for your nice work!
I'm confused about `the robosense data` you shared, whether the header timestamp is frame head or frame end?

**Comment by HViktorTsoi** [comment]
Hi, the raw data of robosense is collected from an old rs16 LiDAR with earlier version of the LiDAR driver, and the timestamps of the points in 1 frame may not be stored in order in some circumstances, therefore we write a [converter](https://github.com/HViktorTsoi/PV-LIO/blob/master/src/converter/rs_to_velodyne.cpp) to handle this. In the converted point cloud msg,  **the msg header timestamp is the time of the earliest point in 1 frame**.

**Comment by HViktorTsoi** [comment]
The converter basically conver the robosense point cloud to a standard velodyne point cloud format, you may refer to this repo https://github.com/HViktorTsoi/rs_to_velodyne

**Comment by HViktorTsoi** [comment]
If you are testing the shared data with your own algorithm, you may run the converer node alone, and then use the converted point cloud msg and the raw imu msg for testing.

**Comment by chengwei0427** [comment]
Hi, Dear author,
The frame header timestamp is frame end, and I can run my program with the shared data successful.
![image](https://github.com/HViktorTsoi/PV-LIO/assets/20199999/3813e75f-f1f9-487b-8b47-0d4693bc8ab2)
Problem solved!
Thanks again.
