### ISSUE TITLE
run error。

### ISSUE THREAD

**Issue by linClubs** [HViktorTsoi/PV-LIO#5]
我在ubuntu20.04，跑自己的voledyne数据，终端输入如下：我应该怎么处理这种情况

![2](https://github.com/HViktorTsoi/PV-LIO/assets/62087085/01bfa071-7797-40a2-9817-944a64a7a257)

**Comment by linClubs** [comment]
这是我运行环境 ubuntu-20.04， eigen-3.3.7， pcl-1.10， gstam-4.1.1，使用的velodyne雷达，我应该怎么解决上面的问题，谢谢

![4](https://github.com/HViktorTsoi/PV-LIO/assets/62087085/8768ad48-4e82-4af8-9e03-cb607eb9eae2)

**Comment by HViktorTsoi** [comment]
Did it fail on the demo robosense rosbag?

**Comment by linClubs** [comment]
感谢您的回复。我测试了2022-08-30-20-37-43_2.bag数据包
报错一样的， 然后我增大了 down_sample_size与 voxel_size，还是一样的错误。rviz也没显示
![2023-07-18 11-20-33屏幕截图](https://github.com/HViktorTsoi/PV-LIO/assets/62087085/3ce84d71-1d41-470c-b66a-d7b2d439f789)

增大了 down_sample_size与 voxel_size，我测试我自己的velodyne数据集，rviz有显示点云，但终端也报同样的错误了
![5](https://github.com/HViktorTsoi/PV-LIO/assets/62087085/67051d7d-2e9b-425a-a6c3-bec8e6e3d23a)

**Comment by linClubs** [comment]
> Did it fail on the demo robosense rosbag?
感谢您开源的工作，我刚刚测试一下2022-08-30-20-37-43_2.bag数据包。这是终端输出结果https://github.com/HViktorTsoi/PV-LIO/issues/5#issuecomment-1639282623，还是报错

**Comment by HViktorTsoi** [comment]
> 感谢您的回复。我测试了2022-08-30-20-37-43_2.bag数据包 报错一样的， 然后我增大了 down_sample_size与 voxel_size，还是一样的错误。rviz也没显示 ![2023-07-18 11-20-33屏幕截图](https://user-images.githubusercontent.com/62087085/254129452-3ce84d71-1d41-470c-b66a-d7b2d439f789.png)
> 
> 增大了 down_sample_size与 voxel_size，我测试我自己的velodyne数据集，rviz有显示点云，但终端也报同样的错误了 ![5](https://user-images.githubusercontent.com/62087085/254130028-67051d7d-2e9b-425a-a6c3-bec8e6e3d23a.png)

Please test the 2022-08-30-20-33-52_0.bag, 2022-08-30-20-37-43_2.bag can't be played alone.

**Comment by HViktorTsoi** [comment]
Seems like a common issue for Ubuntu 20.04, we are trying reproducing the issue in this environment.

**Comment by linClubs** [comment]
> Seems like a common issue for Ubuntu 20.04, we are trying reproducing the issue in this environment.

我测试了2022-08-30-20-33-52_0.bag。跟测试我的数据一样，跑几秒终端就报错了，可能在20.04上的还需要调试一下，感谢您的开源
![2023-07-18 15-20-37屏幕截图](https://github.com/HViktorTsoi/PV-LIO/assets/62087085/aff5e14a-e200-45e3-adb1-0a805a0380ad)

**Comment by linClubs** [comment]
> We've pushed a fix for this, please refer to [#3 (comment)](https://github.com/HViktorTsoi/PV-LIO/issues/3#issuecomment-1640066605)
感谢大佬的工作。已经测试通过^_^
![2023-07-19 13-02-07屏幕截图](https://github.com/HViktorTsoi/PV-LIO/assets/62087085/e75d767e-ed19-4d74-8255-53c56925dd11)
